### ISSUE TITLE
[bug] pushy and default block behaviour does not work

### ISSUE THREAD

**Issue by cachesdev** [simeydotme/svelte-range-slider-pips#157]
### Describe the bug

moving around selectors wont respect either block or pushy, instead they will simply go over the other selector.
it will also generate a whole lot of svelte warnings. bug is most likely related to svelte5.

### Link To Reproduce

[repl](https://svelte.dev/playground/hello-world?version=5.9.0#H4sIAAAAAAAAA42PwW7CMBBEf2W1ZxIILZcUUPsLcCQcnLA0lhzb8m5oUZR_r50gtap66HVm38zsgFZ1hCUGZd8J6l7EWYYPZwV8zy24ACzOA6mmddJSwAVetSHG8jSg3H2CkxD1R9Sb9znfyEjSasX0l97EBrISY3DLTdBe9pWtRHfeBYFDWnM0-kIBrsF1UOFMZtPOjCcr89rz61Ne5M8VviTckMBNmZ64gB2cNgsoVudfzjo5xSpam2Rtl9_11rr57XvUf26otb2UM74bHgUjLCPzz-v1OOdOTHxf6FOwlNDTeB6_ADWbxxWFAQAA)

#### Steps to reproduce the behavior:

pick a selector, and try to go past the other one.

#### Expected behavior

1- selector gets blocked
2- in pushy mode, selector gets pushed

#### Device/Environtment

discovered it on android webview, also happens in firefox and chrome. firefox gets really laggy.

**Comment by simeydotme** [comment]
you need to add `range` property for that to work :) 

https://svelte.dev/playground/hello-world?version=5.9.0#H4sIAAAAAAAAE4WQwW6DQAxEf8XyGUhImwslUfoL7TGbAxCnrATe1dqkjRD_Xi20alRV6nVGb2bsEbnqCQsMFb8R1IOqY4F3xwp-kBZcAFHngaqmddpSwAQvtiPB4jii3nyEo4DJd9Sz95lcqdOo1ZXQX3rjWIlVsMBSmmC97g0btb13QeElrnnt7JkCXILrweBCpvPOVGYr9dbL4SHLs0eDTxHvSOFadQNJDjs4bhPI16dfziY6-TqBfButcvVTz-yWs2-Gy_sNteVzseC78atgguVnq73hmYH_oc20xN-hmKDSh2KhYaDpNH0CVO_otpIBAAA=

**Comment by simeydotme** [comment]
hmmm.....

but....

I see the warning issue (with the perf isuse, too)... the performance/lag is being caused by the thousands of `console.warn()` ... and those warnings are coming from Svelte 5.9.0 ... if you change it to 5.1.0 it is not causing any problems;

https://svelte.dev/playground/hello-world?version=5.1.0#H4sIAAAAAAAAE4WQwW6DQAxEf8XyGUhImwslUfoL7TGbAxCnrATe1dqkjRD_Xi20alRV6nVGb2bsEbnqCQsMFb8R1IOqY4F3xwp-kBZcAFHngaqmddpSwAQvtiPB4jii3nyEo4DJd9Sz95lcqdOo1ZXQX3rjWIlVsMBSmmC97g0btb13QeElrnnt7JkCXILrweBCpvPOVGYr9dbL4SHLs0eDTxHvSOFadQNJDjs4bhPI16dfziY6-TqBfButcvVTz-yWs2-Gy_sNteVzseC78atgguVnq73hmYH_oc20xN-hmKDSh2KhYaDpNH0CVO_otpIBAAA=

.... I don't know what Svelte have changed but it seems like it is _ALMOST_ breaking change, and a little worrying to say the least.
