### ISSUE TITLE
Feature Request: Specify Pip Values

### ISSUE THREAD

**Issue by noslouch** [simeydotme/svelte-range-slider-pips#45]
Hi there. Great component. The UI is very slick! I'd like to use this in a project, but I want to only show pips for specified values.  This is similar to -- but not the same as -- #9.

I'd be happy to open a PR to implement a new prop `pipValues` that accepts a an array of values, each of which represent a value at which to display a pip.

The native HTML range input [supports this feature](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range#a_range_control_with_hash_marks) via a related `<datalist/>` , which accepts a list of `<option/>` elements. Each `<option/>` element has a `value` attribute that corresponds to a hash mark (or pip).

My use case is generating a range slider with hash marks that represent deciles of data, similar to this native implemenation:
![image](https://user-images.githubusercontent.com/2090382/137796986-ca2dd79f-9346-4bbc-adb9-98242af202dd.png)

It's a way to show the distribution of a dataset. 

I'd be happy to open a PR attempting this feature if it's something you'd accept.

**Comment by simeydotme** [comment]
Hi @noslouch  .... thanks for the comments!

[Firstly, is using CSS not applicable for you? ](https://svelte.dev/repl/105d28971dfb436e98eb7b2e8d090cde?version=3.44.1)
ie: are you saying you want only specific values to be selectable?

I actually had a local branch where I was playing with another idea (easing functions for values) that would allow pips / values to be grouped up at large numbers (like 5k,10k,100k) but spread out at small numbers (1,2,5,10) to allow easier selection of smaller numbers in a price-slider for example. This required a `Function` to be passed to the `step` and `pipstep` property instead of a `Number` .. the issue I ran into was mostly related to the easing functions not being reversible due to SquareRoots and stuff.

The main issue of restricting selections to an arbitrary array of values (I'd prefer a function) is that it would require a fairly heavy re-write of the component to allow providing functions for the `alignValueToStep()` method, and also the `pipstep` and `step` placement algorithm which would ultimately reduce the performance somewhat.

If you fancy a challenge and would find it fun, please feel free to give it a go ... but the requirements would be;

- [ ] work without breaking backwards compat
- [ ] accepts a function that returns true if a pip should be drawn _(could be like `(value,index) => [1,2,3].includes(val);`)_
- [ ] allows clicking of pip-values
- [ ] try to keep it lightweight
- [ ] make sure the performance / responsiveness isn't heavily affected

But if you're not confident on this, I may explore it later. But no promises on the date/feasibility.

**Comment by simeydotme** [comment]
Oh ... wait ... @noslouch  .... I just realised ...
try this;

https://svelte.dev/repl/d777b85ba4c9493a8169676adbab1fa6?version=3.44.1

it's a bit hacky, but it works for UI. 
But you'd need backend validation.

**Comment by noslouch** [comment]
HIya @simeydotme . CSS wouldn't work b/c the location of the ticks are dynamic per range slider. Both example expressing the pip locations in the CSS statement, and AFAIK we can't pass JS vars into the CSS in svelte (maybe I'm wrong?).

I'm happy to take a look at this! But... not promises either ;)

**Comment by simeydotme** [comment]
Actually if you're motivated enough you can make the CSS dynamic ;) but it's not intuitive or simple

**Comment by simeydotme** [comment]
@noslouch as there was no movement on this, I updated the REPL to handle the scenario I believe you've described;

https://svelte.dev/repl/d777b85ba4c9493a8169676adbab1fa6?version=3.44.1

so I think I'll close this for now, but keep in mind the original request for any future major version.
Thanks.
