### ISSUE TITLE
[bug] Using the slider for floating point values

### ISSUE THREAD

**Issue by SeeringPhil** [simeydotme/svelte-range-slider-pips#47]
**Describe the bug**
Not sure whether this is a bug or a feature request. 

I am trying to use the component to choose a number with decimal point values. However, if I set steps as a decimal value, for example doing the following : 

```svelte
<RangeSlider min="0" max="1" step="0.2" bind:values={sensitivity} float=false pips />
```

Then I have the error : `aligned.toFixed() is not a function.`

I know I could probably still use this component and use the formatters to go from 0 to 100 or 0 to 1000 and then format the values by dividing by 100 or 1000, and get the functionnality. However, I was wondering if I was overlooking a cleaner way to go about handling this?

Thanks a lot!

**To Reproduce**

- ⛔ **Fork [this REPL as a reduced test case](https://svelte.dev/repl/e5186330fc624fb397c89b719e2fecdc?version=3.44.0)**

**Comment by simeydotme** [comment]
Thanks @SeeringPhil for opening an issue!
And extra Kudos for reading the contribution guidelines! 👏 

Actually I think the component is fine, but there's a scenario you've run into that I've seen others run into _(and I have myself with other components, too)_... 

When providing and `Integer` or `Float` as a component prop, it should be wrapped in `{ braces }`, because a normal HTML attribute wrapped in quotes (or not) counts as a `String`. Libraries like Vue and Svelte use `{ braces }` to notify the JavaScript engine to infer the type instead of treating as a `String`. [Here's an example of that in action;](https://svelte.dev/repl/0dbe83707d6941acb36838bdc6ab8104?version=3)

I don't know if I could safely coerce the values, but for now the documentation has enough statements about the values being `Number` type, and [the documentation (although not complete) has clear examples of min/max/step being used with the `{ braces }` ](https://simeydotme.github.io/svelte-range-slider-pips/#min--max) so I think it's OK for now?

**Comment by SeeringPhil** [comment]
Ohhh wow, thank you very much for the detailed explanation, I've learned something new here. 

I'm not used to working on frontend that much but I was confused since it was working with my other use cases using the strings. Also, when passing styling arguments, you can use floats (for instance when specifying 1.5rem) so I guess that's why I thought it made sense 😅

Since all the use cases for this library are using numbers, I guess you could try to coerce the values as numbers? Or is that a bad practice? 
Alternatively, is there a pattern in Svelte where you can force the passing of a specific type of arguments, thus forcing users to always use the brackets? 

It's OK for now of course, now that I know it and it's documented here the issue is moot. Again, thank you very much!

I started a fork in a codespace to add an example with floating point values & highlight the importance of using the brackets for these type of values to your documentation, but I noticed only afterwards that it wasn't hosted on the Github repo 😅
