### ISSUE TITLE
Add onEnd property to provide user-defined callback

### ISSUE THREAD

**Issue by jasongitmail** [simeydotme/svelte-range-slider-pips#6]
Feature suggestion. This would allow sliders to act on the new values (e.g. send an HTTP request, update a Store, etc).

Should just require adding a user-defined callback as an export & invoking with the new values as params here: https://github.com/simeydotme/svelte-range-slider-pips/blob/main/src/RangeSlider.svelte#L412 

Let me know if you'd like a PR for this.

**Comment by simeydotme** [comment]
thanks @jasongitmail for the suggestion!
I did wrestle with this internally regarding events... especially as this is based on my previous work with the jQuery UI slider which is massively event oriented. 

The thing which I always came back to though is that this is primarily a reactive component, meaning that the reactive values changing inside of the Svelte app should be driving events, not the interaction itself if I'm not mistaken. Thus using something like below should be the idiomatic way to react to state changes
```js
$: values && () => {
  // do your trigger here
};
``` 

**but** I do recognition that I've declared this component usable without Svelte as a standalone JS component... so I guess the events would be important there.

--- 
As with #5 I think I'll do a little testing how well the tree shaking is working before I work on these new feature... because I want to make the thing only shipping features being used (ie; events, and such)

**Comment by jasongitmail** [comment]
```js
$: values && () => {
  // do your trigger here
};
```

I'm new to Svelte, but that looks like it would update every time `values` changes, which means multiple invocations while the handle is adjusted until it is released. 

That's problematic for use cases that cause a side effect, such as sending an AJAX request, which need to be invoked only when the _final_ value is known. 

I agree about not adding other events, keep it light, let Svelte do the work when possible. But if I'm not mistaken, only the range component itself has knowledge that the slide action is done, so it would have to invoke a method, like proposed here, to communicate this externally.

This could be a very lightweight. It's just a matter of accepting an `onEnd` prop, then at the proper moment, check if the `onEnd` param is a function and invoking it if it is, passing the new slider values. ~2-4 lines?

**Comment by mnashmi** [comment]
i agree with this request very helpful to avoid multiple callbacks & triggers with $: values ..

i ended up changing the following code:

`RangeSlider.svelte`

`line 1`
```
+  import { afterUpdate, createEventDispatcher } from 'svelte';
+  const dispatch = createEventDispatcher();
```
`line:406`
```
  function sliderInteractEnd(e) {
    handlePressed = false;
  + dispatch("done");
  }
```

Now you have:
`<RangeSlider on:done=...`

**Comment by simeydotme** [comment]
thanks @mnashmi I'll take a look at the impact of that, compared to a simple callback :)

**Comment by rster2002** [comment]
I think the method @mnashmi suggested would be the way to go instead of a simple callback as it's the build-in way to emit events in svelte. But that's just my opinion. Either way, it would be really helpful to have some way to handle these events.

**Comment by jasongitmail** [comment]
We should avoid over-engineering or adding unneeded dependencies. Event emitters aren't needed to solve this. A simple function callback works nicely.

**Comment by simeydotme** [comment]
@jasongitmail @mnashmi @rster2002 I have pushed `1.6.0` with the event dispatches.
See https://github.com/simeydotme/svelte-range-slider-pips/blob/main/README.md#slider-events-dispatched for how to use.

A few points;

1. @mnashmi 's approach https://github.com/simeydotme/svelte-range-slider-pips/issues/6#issuecomment-757355302 is not really a good one, as the `sliderInteractEnd()` event doesn't fire when the user ends interaction off the slider (ie: body).
2. I also added an `on:change` which only fires when the values are changed, and different
3. I've added the appropriate, normalised, `event.detail` values which are inspired by jQueryUI Slider (which this component is inspired by) for ease of use.
4. I went with **createEventDispatcher** instead of callbacks, because after doing both approaches I found the dispatcher was only marginally heavier and not something that worried me (see below). I also preferred the idiomatic approach.

Please let me know if this is satisfactory, and if you have any comments/problems.
best, Simon.

---
## size before:
```
│   Bundle Size:  73.2 KB
│   Minified Size:  23.69 KB
│   Gzipped Size:  8.07 KB

size with dispatcher:

│   Bundle Size:  75.49 KB
│   Minified Size:  24.32 KB
│   Gzipped Size:  8.31 KB

size with callbacks:

│   Bundle Size:  75.02 KB
│   Minified Size:  24.18 KB
│   Gzipped Size:  8.24 KB
```

**Comment by rster2002** [comment]
Changes look awesome! Thanks for incorporating it 👍

**Comment by saravanabalagi** [comment]
I did `Ctrl + F` and events, was surprised that there were no matches. I tracked it down here after some googling to only know that it's already there 😩 in README! @simeydotme Kindly add this to the Github pages, Thanks.
