### ISSUE TITLE
How can I bind events to the slider handles? 

### ISSUE THREAD

**Issue by hessel-bb** [simeydotme/svelte-range-slider-pips#67]
I want to add an on mouseup event to the slider handles. I tried the following but no luck:
```
<script>
import RangeSlider from "svelte-range-slider-pips";
export let hits = [];
let price;
async function filterOnPrice() {
        index.search('', {
            filters: `price:${price[0]} TO ${price[1]}`,
            facetFilters: 'collections:racefietsen',
        }).then(( res ) => {
            console.log(res);
            hits = res.hits
        });
    }
<script>
<div>
    <RangeSlider range pushy min={0} bind:values={price} on:mouseup={ () => filterOnPrice()} max={5000} float prefix="€" 
      id="price"/>
</div>
```

**Comment by simeydotme** [comment]
May I ask what you're trying to achieve? 

I can't imagine why you would want to bind events to a slider handler inside of a svelte application, as it is a reactive data app... so whatever you're trying to do, you could use a reactive statement instead of a mouse event?

Let me know your desired outcome and I'm sure we can sort it :)

**Comment by simeydotme** [comment]
https://svelte.dev/repl/8ffd012c92144a1bac4a7312d9d5305a?version=3.46.4

**Comment by simeydotme** [comment]
Closing as no response to my query
