### ISSUE TITLE
[question] TypeError: SvelteRangeSliderPips is not a constructor

### ISSUE THREAD

**Issue by lpoupet** [simeydotme/svelte-range-slider-pips#70]
**Describe the bug**
Testing a svelte component that include `RangeSlider` does not works. I have an error : 
`TypeError: SvelteRangeSliderPips is not a constructor`.

I'm testing a "classic" implementation with :
```js
<script>
  import RangeSlider from "svelte-range-slider-pips";
</script>

<RangeSlider values={[50]} pips />
```

If I try to fork project and implement some tests with jest and testing library, I don't manage to make it works. Getting error : 
`Unrecognized option 'sourcemap'`.

**To Reproduce**
Just try to test `RangeSlider` component in a svelte app.
For the second problem, you can fork : [https://github.com/lpoupet/svelte-range-slider-pips](https://github.com/lpoupet/svelte-range-slider-pips)

Run `npm run test`

**Expected behavior**
No error

**Comment by simeydotme** [comment]
hi @lpoupet 

I don't quite follow what you mean by "classic". Are you meaning that you simply trying to import into a Svelte project? And if so, Svelte 2 or Svelte 3, or SvelteKit ?

Anyway, I cannot replicate, see; https://stackblitz.com/edit/vitejs-vite-4gezgs?file=src%2FApp.svelte&terminal=dev for example.
Please can you produce a reduced test case for me?

---

Secondly, I'm not sure what your issue is with sourcemap, but I think it's unrelated to this component and is an issue with the way you're loading Svelte. as `sourcemap` is a Svelte option, not a `RangeSlider` option. (https://svelte.dev/docs#compile-time-svelte-compile)
