### ISSUE TITLE
[feature] events are missing in the docs page

### ISSUE THREAD

**Issue by paulovieira** [simeydotme/svelte-range-slider-pips#81]
**Describe the feature**
The [docs page](https://simeydotme.github.io/svelte-range-slider-pips/) is wonderful! But the [slider events](https://github.com/simeydotme/svelte-range-slider-pips#slider-events-dispatched) seem to be missing.

**Explain it's value / reasoning**
The events are a fundamental feature for a library like this.

**Comment by simeydotme** [comment]
Hi @paulovieira  , thanks, yes I added the event handlers after the docs page was created. 
Actually there's a fair amount missing but I never seem to find the energy to update it :(

One thing I would add, though, is that the Docs page is for the Svelte version, and really the events are not especially useful for the Svelte (reactive) use-case, as one should really be using reactive statements instead of event listeners.

**Comment by simeydotme** [comment]
this has bee live for a while :D
