### ISSUE TITLE
[bug] zoom misaligns handle

### ISSUE THREAD

**Issue by mustafa0x** [simeydotme/svelte-range-slider-pips#95]
**Describe the bug**
Adding CSS's `zoom` (eg `body {zoom: 1.5}`) to a containing element causes the handle to move away from the cursor.

https://user-images.githubusercontent.com/1473102/219553606-dcefd1d8-41d6-43cd-ab1b-906b2aa73a8e.mp4

**To Reproduce**

- https://svelte.dev/repl/ed6727508474481590f1b14674e9210a?version=3.32.1

**Comment by simeydotme** [comment]
oh yikes ...

**Comment by simeydotme** [comment]
ah, ok, as I suspected, it's non-standard;
https://developer.mozilla.org/en-US/docs/Web/CSS/zoom

Please can you describe your use-case for Zoom, @mustafa0x ?

**Comment by mustafa0x** [comment]
To automatically zoom-in a simple web app. It's non-standard but widely supported (95.5%).

**Comment by simeydotme** [comment]
I've confirmed that the slider is working well with a `transform: scale(2)` on the `<body>` or `<main>` which is actually better for performance... any chance you can use that?

**Comment by mustafa0x** [comment]
I was indeed using `scale: 2`, but it required a _lot_ of custom calculations, while `zoom` mimics the browser's zoom really well.

I think the fix here is to multiply `clientPos.clientX` by the zoom value. I'll try to check this soon.

I appreciate you looking into this, and also understand if it isn't a priority.

**Comment by simeydotme** [comment]
> while zoom mimics the browser's zoom really well.

This piqued my intrigue (I thought I had tested this a long time ago) and I tried zooming on the demo site (using browser zoom); the calcs are fine. So not that it changes much, but the assertion is a little off. 

Please do investigate if you are inclined, my concern is dom traversal and style property access on the slide event. Not only is it extraneous bytes for a feature that _should_ not be used, but it is adding performance overhead for everyone who doesn't use it.

One thing I might consider; exposing the x/y values to the custom property API, so that you can edit the CSS to use `calc( var(--handleX) * var(--myZoom) );` in the CSS to override the x/y position. I'd need to see if it conflicts with the existing css/animations, though.

**Comment by mustafa0x** [comment]
> This piqued my intrigue (I thought I had tested this a long time ago) and I tried zooming on the demo site (using browser zoom); the calcs are fine. So not that it changes much, but the assertion is a little off.

I either misunderstood this or failed to express myself earlier. I'm saying that `scale` (or `transform: scale`, they are the same) isn't a one-line solution like zoom is.

Eg, see the google homepage

**zoom: 2**
![image](https://user-images.githubusercontent.com/1473102/221745181-82af0fe9-4719-4aec-bb63-98a54725a98a.png)

**scale: 2**
![image](https://user-images.githubusercontent.com/1473102/221745211-e748bf15-0fb0-45b9-9dbc-f9da37676efa.png)

**Comment by mustafa0x** [comment]
Seems like google plans to remove `zoom` support at some point; closing.

https://groups.google.com/a/chromium.org/g/blink-dev/c/V7q43bgutbo/m/-7jneTl8CQAJ
